@file:Suppress("unused")

package com.purascents.base.analytics

class AnalyticsKeyConstants {

    companion object {
        const val BUTTON_TAPPED_KEY = "Button Tapped"
        const val BUTTON_TEXT_KEY = "button_text"
        const val FLOW_KEY = "flow"
        const val EVENT_TYPE_KEY = "event_type"
        const val CUSTOM_PROPERTIES_KEY = "custom_properties"
        const val SCREEN_NAME_KEY = "screen_name"
        const val SCREEN_VIEWED_KEY = "Screen"
        const val APP_EVENT_KEY = "App Event"
        const val EVENT_NAME_KEY = "event_name"
        const val VARIANT_KEY = "variant"
        const val VARIANT_SKU_KEY = "variant_sku"
        const val DEVICE_ID_KEY = "device_id"
        const val DIFFUSER_ID_KEY = "diffuser_id"
        const val DIFFUSER_NAME_KEY = "diffuser_name"
        const val INPUT_METHOD_KEY = "input_method"
        const val METHOD_KEY = "method"
        const val PAGE_KEY = "page"
        const val BAY_KEY = "bay"
        const val RUNTIME_KEY = "runtime"
        const val FRAGRANCE_NAME_KEY = "fragrance_name"
        const val CONFLICT_RUNNING_KEY = "conflict_with_running_schedule"
        const val CONFLICT_SCHEDULE_KEY = "conflict_with_future_schedule"
        const val SERVICE_KEY = "service"
        const val ROOM_NAME_KEY = "room_name"
        const val ROOM_TYPE_KEY = "room_type"
        const val INTENSITY_KEY = "intensity"
        const val FRAGRANCE_SKU_KEY = "fragrance_sku"
        const val FRAGRANCE_TIMESTAMP_KEY = "fragrance_added_timestamp"
        const val FRAGRANCE_REMAINING_KEY = "fragrance_remaining"
        const val WEARING_TIME_KEY = "wearing_time"
        const val OLD_WEARING_TIME_KEY = "old_wearing_time"
        const val IS_RUNNING_KEY = "is_running"
        const val SKU_KEY = "sku"
        const val ON_KEY = "on"
        const val VALUE_KEY = "value"
        const val COLOR_KEY = "color"
        const val MODE_KEY = "mode"
        const val EVENT_KEY = "event"
        const val DAYS_SINCE_REFILL = "days_since_refill"
        const val STATUS_KEY = "status"
        const val TIME_ZONE_KEY = "time_zone"
        const val SWAPPED_KEY = "swapped"
        const val BRAND_KEY = "brand"
        const val DEVICE_SETUP_VERSION_KEY = "device_setup_version"
        const val EMAIL_KEY = "email"
        const val TYPE_KEY = "type"
        const val STATE_KEY = "state"
        const val PLACE_KEY = "place"
        const val RESULT_KEY = "result"
        const val VIEW_TYPE_KEY = "view_type"
        const val ACTION_KEY = "action"
        const val REASON_KEY = "reason"
        const val RATING_KEY = "rating"
        const val CLICK_SOURCE_KEY = "click_source"
        const val DEVICE_TYPE_KEY = "device_type"
        const val DIFFUSER_TYPE_KEY = "diffuser_type"
        const val START_TIME_KEY = "start_time"
        const val END_TIME_KEY = "end_time"
        const val CURRENT_FIRMWARE_KEY = "current_firmware"
        const val SUCCESS_KEY = "success"
        const val SIZE_KEY = "size"
        const val DEVICE_COUNT_KEY = "device_count"
        const val START_KEY = "start"
        const val END_KEY = "end"
        const val LIGHT_KEY = "light"
        const val DAYS_KEY = "days"
        const val NAME_KEY = "name"
        const val HW_KEY = "hw"
        const val FW_KEY = "fw"
        const val NETWORK_SECURED_KEY = "network_secured"
        const val RSSI_KEY = "rssi"
        const val ERROR_KEY = "error"
        const val BLUETOOTH_ENABLED_KEY = "bluetooth_enabled"
        const val BLUETOOTH_APP_PERMISSION_KEY = "bluetooth_app_permission"
        const val DIFFUSERS_KEY = "diffusers"
        const val BLUETOOTH_NAME_KEY = "bluetooth_name"
        const val IS_ONBOARDED_KEY = "is_onboarded"
        const val APP_PERMISSIONS_KEY = "app_permissions"
        const val APP_VERSION_KEY = "app_version"
        const val PLATFORM_KEY = "platform"
        const val FEATURE_FLAGS_KEY = "ld_values"
        const val DISPLAY_NAME_KEY = "displayName"
        const val BLUETOOTH_KEY = "bluetooth"
        const val NOTIFICATION_KEY = "notification"
        const val LOCATION_KEY = "location"
        const val CAMERA_KEY = "camera"
        const val PAYLOAD = "payload"
    }
}
